services:
  backend:
    image: Djamel2s/ci-ci-pipeline:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - appbridge

  frontend:
    image: Djamel2s/ci-ci-pipeline:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - appbridge

networks:
  appbridge:
    driver: bridge

